Bidster/Entities/Events/Event.cs
using Bidster.Entities.Users;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Bidster.Entities.Events
{
    public class Event 
    {
        public int Id { get; set; }
        
        [Required, MaxLength(100)]
        public string Slug { get; set; }
        [Required, MaxLength(100)]
        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime StartOn { get; set; }
        public DateTime EndOn { get; set; }

        public DateTime DisplayOn { get; set; }

        public bool HideBidderNames { get; set; }

        public decimal? DefaultMinimumBidAmount { get; set; }

        public int OwnerId { get; set; }
        [ForeignKey(nameof(OwnerId))]
        public virtual User Owner { get; set; }

        public DateTime CreatedOn { get; set; }


        public bool IsBiddingOpen(DateTime date) => StartOn <= date && EndOn > date;

        public virtual List<EventUser> Users { get; set; }
    }
}

Bidster/Entities/Events/EventUser.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Bidster.Entities.Users;

namespace Bidster.Entities.Events
{
    public class EventUser
    {
        public int Id { get; set; }

        public int EventId { get; set; }
        [ForeignKey(nameof(EventId))]
        public virtual Event Event { get; set; }

        public int UserId { get; set; }
        [ForeignKey(nameof(UserId))]
        public virtual User User { get; set; }

        public bool IsAdmin { get; set; }

        public DateTime CreatedOn { get; set; }
    }
}

Bidster/Models/Events/AllBidsReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bidster.Models.Bids;

namespace Bidster.Models.Events
{
    public class AllBidsReportViewModel
    {
        public EventModel Event { get; set; }

        public List<ProductGroupModel> Products { get; set; } = new List<ProductGroupModel>();

        public class ProductGroupModel
        {
            public int Id { get; set; }
            public string Name { get; set; }

            public List<BidModel> Bids { get; set; }
        }

    }
}

Bidster/Models/Events/EditEventViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Bidster.Models.Events
{
    public class EditEventViewModel
    {
        public int Id { get; set; }
        
        [Required, MaxLength(100)]
        public string Name { get; set; }

        [Display(Name = "Event description")]
        public string Description { get; set; }

        [Display(Name = "Start date/time")]
        public DateTime StartOn { get; set; }
        [Display(Name = "End date/time")]
        public DateTime EndOn { get; set; }
        [Display(Name = "Display date/time")]
        public DateTime DisplayOn { get; set; }

        [Display(Name = "Hide bidder names")]
        public bool HideBidderNames { get; set; }
        [Display(Name = "Default min bid amount")]
        public decimal? DefaultMinimumBidAmount { get; set; }
    }
}

Bidster/Controllers/EventUsersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Bidster.Data;
using Bidster.Entities.Events;
using Bidster.Entities.Users;
using Bidster.Models;
using Bidster.Models.EventUsers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Bidster.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Authorize]
    [Route("events/{evtSlug}/users")]
    public class EventUsersController : Controller
    {
        private readonly BidsterDbContext _dbContext;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<EventUsersController> _logger;

        public EventUsersController(BidsterDbContext dbContext,
            UserManager<User> userManager,
            ILogger<EventUsersController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index(string evtSlug)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            if (evt == null)
            {
                _logger.LogInformation("Event with slug '{slug}' not found", evtSlug);
                return NotFound();
            }

            var evtUsers = await _dbContext.EventUsers.Include(x => x.User)
                .Where(x => x.EventId == evt.Id)
                .OrderBy(x => x.User.FullName)
                .Select(x => x.ToEventUserModel())
                .ToListAsync();

            var model = new EventUserListViewModel
            {
                Event = evt.ToEventModel(),
                Users = evtUsers
            };

            return View("Index", model);
        }

        [HttpPost("new")]
        public async Task<IActionResult> Create(string evtSlug, EventUserListViewModel model)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            if (evt == null)
            {
                _logger.LogInformation("Event with slug '{slug}' not found", evtSlug);
                return NotFound();
            }

            try
            {
                var user = await _userManager.FindByEmailAsync(model.NewUserEmail);
                if (user == null)
                {
                    ModelState.AddModelError("NewUserEmail", "User with this email does not exist.");
                    return await Index(evtSlug);
                }

                var existingUser = await _dbContext.EventUsers.SingleOrDefaultAsync(x => x.EventId == evt.Id && x.UserId == user.Id);
                if (existingUser != null)
                {
                    ModelState.AddModelError("NewUserEmail", "User is alredy a member of this event.");
                    return await Index(evtSlug);
                }

                var evtUser = new EventUser
                {
                    Event = evt,
                    User = user,
                    IsAdmin = model.NewUserIsAdmin,
                    CreatedOn = DateTime.Now
                };

                _dbContext.EventUsers.Add(evtUser);
                await _dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new { slug = evtSlug });
            }
            catch(Exception ex)
            {
                _logger.LogError(ex, "Error adding user '{user}' to event {id}", model.NewUserEmail, evt.Id);

                ModelState.AddModelError("", "Error adding user to event");
                return await Index(evtSlug);
            }

        }

        [HttpGet("delete")]
        public async Task<IActionResult> Delete(string evtSlug, int id)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            if (evt == null)
            {
                _logger.LogInformation("Event with slug '{slug}' not found", evtSlug);
                return NotFound();
            }

            //try
            {
                var existingUser = await _dbContext.EventUsers.SingleOrDefaultAsync(x => x.EventId == evt.Id && x.Id == id);
                if (existingUser != null)
                {
                    _dbContext.EventUsers.Remove(existingUser);
                    await _dbContext.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index), new { evtSlug });

            }
        }
    }
}

Bidster/Controllers/ProductsController.cs
using Bidster.Data;
using Bidster.Entities.Products;
using Bidster.Entities.Users;
using Bidster.Models;
using Bidster.Models.Products;
using Bidster.Services.FileStorage;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.IO;
using System.Threading.Tasks;

namespace Bidster.Controllers
{
    [ApiExplorerSettings(IgnoreApi = true)]
    [Route("events/{evtSlug}/products")]
    public class ProductsController : Controller
    {
        private readonly BidsterDbContext _dbContext;
        private readonly UserManager<User> _userManager;
        private readonly IFileService _fileService;
        private readonly IAuthorizationService _authorizationService;
        private readonly ILogger<ProductsController> _logger;

        public ProductsController(BidsterDbContext dbContext,
            UserManager<User> userManager,
            IFileService fileService,
            IAuthorizationService authorizationService,
            ILogger<ProductsController> logger)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _fileService = fileService;
            _authorizationService = authorizationService;
            _logger = logger;
        }

        [HttpGet("{slug}")]
        public async Task<IActionResult> Details(string evtSlug, string slug)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            if (evt == null)
            {
                _logger.LogInformation("Event slug '{evtSlug}' not found", evtSlug);
                return RedirectToAction("Index", "Events");
            }

            var product = await _dbContext.Products.SingleOrDefaultAsync(x => x.EventId == evt.Id && x.Slug == slug);
            if (product == null)
            {
                _logger.LogInformation("Product slug '{slug}' not found or does not belong to event '{evtSlug}'", slug, evtSlug);
                return RedirectToAction("Details", "Events", new { slug = evtSlug });
            }

            var user = await _userManager.GetUserAsync(User);

            var model = new ProductDetailsViewModel();
            model.Event = ModelMapper.ToEventModel(evt);
            model.Product = ModelMapper.ToProductModel(product);
            
            if (!string.IsNullOrEmpty(product.ImageFilename))
            {
                model.Product.ImageUrl = _fileService.ResolveFileUrl(string.Format(Constants.ImagePathFormat, evt.Slug, product.ImageFilename));
            }

            model.CanUserEdit = (await _authorizationService.AuthorizeAsync(User, evt, Policies.EventAdmin)).Succeeded;


            return View(model);
        }

        [Authorize]
        [HttpGet("new")]
        public async Task<IActionResult> Create(string evtSlug)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            var user = await _userManager.GetUserAsync(User);

            if (evt == null)
            {
                _logger.LogInformation("Could not find event with slug '{slug}'", evtSlug);
                return RedirectToAction("Index", "Events");
            }

            if (!(await _authorizationService.AuthorizeAsync(User, evt, Policies.EventAdmin)).Succeeded)
            {
                return Forbid();
            }

            var model = new EditProductViewModel
            {
                EventId = evt.Id,
                EventSlug = evt.Slug,
                EventName = evt.Name
            };

            if (evt.DefaultMinimumBidAmount.HasValue)
            {
                model.MinimumBidAmount = evt.DefaultMinimumBidAmount.Value;
            }

            return View(model);
        }

        [Authorize]
        [HttpPost("new")]
        public async Task<IActionResult> Create(string evtSlug, EditProductViewModel model)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            var user = await _userManager.GetUserAsync(User);

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            if (evt == null)
            {
                _logger.LogInformation("Could not find event with slug '{slug}'", evtSlug);
                return RedirectToAction("Index", "Events");
            }

            if (!(await _authorizationService.AuthorizeAsync(User, evt, Policies.EventAdmin)).Succeeded)
            {
                return Forbid();
            }

            // Reset event props in case something fails...
            model.EventId = evt.Id;
            model.EventSlug = evt.Slug;
            model.EventName = evt.Name;

            try
            {
                var product = new Product
                {
                    Event = evt,
                    Name = model.Name,
                    Description = model.Description,
                    StartingPrice = model.StartingPrice,
                    MinimumBidAmount = model.MinimumBidAmount,
                    CurrentBidAmount = model.StartingPrice,
                    BuyItNowPrice = model.BuyItNowPrice
                };

                product.Slug = await GenerateSlugAsync(evt.Id, product.Name);

                _dbContext.Products.Add(product);
                await _dbContext.SaveChangesAsync();

                // Save images after the product is created because we need the ID
                if (model.ImageFile != null)
                {
                    product.ImageFilename = GenerateImageFilename(product, model.ImageFile.FileName);

                    var imagePath = string.Format(Constants.ImagePathFormat, evt.Slug, product.ImageFilename);

                    using (var stream = model.ImageFile.OpenReadStream())
                    {
                        await _fileService.SaveFileAsync(imagePath, model.ImageFile.ContentType, stream);
                    }

                    _dbContext.Products.Update(product);
                    await _dbContext.SaveChangesAsync();
                }

                if (model.ThumbnailFile != null)
                {
                    product.ThumbnailFilename = GenerateImageFilename(product, model.ThumbnailFile.FileName, true);

                    var imagePath = string.Format(Constants.ImagePathFormat, evt.Slug, product.ThumbnailFilename);

                    using (var stream = model.ThumbnailFile.OpenReadStream())
                    {
                        await _fileService.SaveFileAsync(imagePath, model.ThumbnailFile.ContentType, stream);
                    }

                    _dbContext.Products.Update(product);
                    await _dbContext.SaveChangesAsync();
                }

                return RedirectToAction("Details", "Events", new { slug = evtSlug });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error adding product '{name}' to event ID {evtId}", model.Name, evt.Id);

                return View(model);
            }
        }

        [Authorize]
        [HttpGet("edit/{id}")]
        public async Task<IActionResult> Edit(string evtSlug, int id)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            var user = await _userManager.GetUserAsync(User);

            if (evt == null)
            {
                _logger.LogInformation("Could not find event with slug '{slug}'", evtSlug);
                return RedirectToAction("Index", "Events");
            }

            if (!(await _authorizationService.AuthorizeAsync(User, evt, Policies.EventAdmin)).Succeeded)
            {
                return Forbid();
            }

            var product = await _dbContext.Products.FindAsync(id);
            if (product == null || product.EventId != evt.Id)
            {
                _logger.LogInformation("Product ID {id} not found", id);
                return RedirectToAction("Details", "Events", new { slug = evtSlug });
            }

            var model = new EditProductViewModel
            {
                Id = id,

                EventId = evt.Id,
                EventSlug = evt.Slug,
                EventName = evt.Name,

                Name = product.Name,
                Description = product.Description,
                StartingPrice = product.StartingPrice,
                MinimumBidAmount = product.MinimumBidAmount,
                BuyItNowPrice = product.BuyItNowPrice,
                HasBids = product.HasBids,

                ImageFilename  = product.ImageFilename,
                ThumbnailFilename = product.ThumbnailFilename
            };

            if (!string.IsNullOrEmpty(model.ImageFilename))
            {
                var path = string.Format(Constants.ImagePathFormat, evt.Slug, product.ImageFilename);
                model.ImageUrl = _fileService.ResolveFileUrl(path);
            }

            if (!string.IsNullOrEmpty(model.ThumbnailFilename))
            {
                var path = string.Format(Constants.ImagePathFormat, evt.Slug, product.ThumbnailFilename);
                model.ThumbnailUrl = _fileService.ResolveFileUrl(path);
            }

            return View(model);
        }

        [Authorize]
        [HttpPost("edit/{id}")]
        public async Task<IActionResult> Edit(string evtSlug, int id, EditProductViewModel model)
        {
            var evt = await _dbContext.Events.SingleOrDefaultAsync(x => x.Slug == evtSlug);
            var user = await _userManager.GetUserAsync(User);

            if (evt == null)
            {
                _logger.LogInformation("Could not find event with slug '{slug}'", evtSlug);
                return RedirectToAction("Index", "Events");
            }

            if (!(await _authorizationService.AuthorizeAsync(User, evt, Policies.EventAdmin)).Succeeded)

Bidster/Views/Events/AllBids.cshtml
@model Bidster.Models.Events.AllBidsReportViewModel

@{
    ViewBag.Title = $"{Model.Event.Name} - All bids";
}

<p>
    <a asp-action="Details" asp-route-slug="@Model.Event.Slug" class="btn btn-outline-secondary">Back to Event</a>
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Product</th>
            <th>Bid time</th>
            <th>Amount</th>
            <th>Bidder</th>
        </tr>
    </thead>
    @foreach(var prodGrp in Model.Products)
    {
        var firstBid = prodGrp.Bids.First();
        <tr>
            <td rowspan="@prodGrp.Bids.Count">
                <strong>@prodGrp.Name</strong>
            </td>
            <td>@firstBid.Timestamp.ToString("g")</td>
            <td>@firstBid.Amount.ToString("c2")</td>
            <td>@firstBid.UserName</td>
        </tr>

        foreach(var bid in prodGrp.Bids.Skip(1))
        {
            <tr>
                @*<td></td>*@
                <td>@bid.Timestamp.ToString("g")</td>
                <td>@bid.Amount.ToString("c2")</td>
                <td>@bid.UserName</td>
            </tr>
        }
    }
</table>

Bidster/Views/Events/Create.cshtml
@model Bidster.Models.Events.EditEventViewModel

@{
    ViewBag.Title = "New Event";
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="Create" method="post">

            <partial name="_EditForm" model="Model" />

            <button type="submit" class="btn btn-primary">Create Event</button>
        </form>
    </div>
</div>

Bidster/Views/Events/Details.cshtml
@model Bidster.Models.Events.EventDetailsViewModel

@{
    ViewBag.Title = Model.Event.Name;
}

@section Jumbotron
{
    <partial name="_EventHeader" model="@Model.Event" />
}

@if (!string.IsNullOrEmpty(Model.Event.Description))
{
    <p class="description">
        @Html.Raw(System.Web.HttpUtility.HtmlDecode(Model.Event.Description))
    </p>
}

<partial name="_EventTimeStatus" model="@Model.Event" />

@if (Model.CanUserEdit)
{
    <div class="my-4">
        <div class="btn-group">
            <div class="btn-group">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Manage <span class="caret"></span>
                </button>
                <div class="dropdown-menu">
                    <a asp-action="Edit" asp-route-id="@Model.Event.Id" class="dropdown-item">Edit Event</a>
                    <a asp-action="Create" asp-controller="Products" asp-route-evtSlug="@Model.Event.Slug" class="dropdown-item">Add New Product</a>
                    <a asp-action="Index" asp-controller="EventUsers" asp-route-evtSlug="@Model.Event.Slug" class="dropdown-item">Manage Event Users</a>
                </div>
            </div>

            <div class="btn-group">
                <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Reports <span class="caret"></span>
                </button>
                <div class="dropdown-menu">
                    <a asp-action="WinningBids" asp-route-slug="@Model.Event.Slug" class="dropdown-item">Winning Bids</a>
                    <a asp-action="AllBids" asp-route-slug="@Model.Event.Slug" class="dropdown-item">View All Bids</a>
                </div>
            </div>
        </div>

    </div>
}

<h2>Items for Sale</h2>

<div class="row products">
    @foreach (var product in Model.Products)
    {
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <a asp-action="Details" asp-controller="Products" asp-route-evtSlug="@Model.Event.Slug" asp-route-slug="@product.Slug">
                    @if (!string.IsNullOrEmpty(product.ThumbnailUrl))
                    {
                        <img class="card-img-top" width="100%" height="225" src="@product.ThumbnailUrl" alt="@product.Name" />
                    }
                    else
                    {
                        <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect fill="#55595c" width="100%" height="100%" /><text fill="#eceeef" dy=".3em" x="50%" y="50%">Thumbnail</text></svg>
                    }
                </a>
                <div class="card-body">
                    <h5 class="card-heading">
                        <a asp-action="Details" asp-controller="Products" asp-route-evtSlug="@Model.Event.Slug" asp-route-slug="@product.Slug">@product.Name</a>
                    </h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <span>
                            <b>@product.CurrentBidAmount.ToString("c2")</b>
                            <small>(@product.BidCount bids)</small>
                        </span>
                        <div class="btn-group">
                            @*<button type="button" class="btn btn-sm btn-outline-secondary">View</button>*@
                            @if (Model.CanUserEdit)
                            {
                                <a asp-action="Edit" asp-controller="Products" asp-route-evtSlug="@Model.Event.Slug" asp-route-id="@product.Id" class="btn btn-sm btn-outline-secondary">Edit</a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Bidster/Views/Events/Edit.cshtml
@model Bidster.Models.Events.EditEventViewModel

@{
    ViewBag.Title = "Edit Event";
}

<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit" asp-route-id="@Model.Id" method="post">
            
            <partial name="_EditForm" model="Model" />

            <button type="submit" class="btn btn-primary">Save Event</button>
        </form>
    </div>
</div>

Bidster/Views/Events/Index.cshtml
@model Bidster.Models.Events.EventListViewModel

@{
    ViewBag.Title = "Events";
}

@if (Model.CanCreateEvent)
{
    <p>
        <a asp-action="Create" class="btn btn-success">New Event</a>
    </p>
}

<table class="table table-sm table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Display On</th>
            <th>Start</th>
            <th>End</th>
        </tr>
    </thead>
    @foreach (var evt in Model.Events)
    {
        <tr>
            <td>
                <a asp-action="Details" asp-route-slug="@evt.Slug">@evt.Name</a>
            </td>
            <td>@evt.DisplayOn.ToString("d")</td>
            <td>@evt.StartOn.ToString("d")</td>
            <td>@evt.EndOn.ToString("d")</td>
        </tr>
    }
</table>

Bidster/Views/Events/WinningBids.cshtml
@model Bidster.Models.Events.WinningBidsReportViewModel

@{
    ViewBag.Title = $"{Model.Event.Name} - Winning bids";
}

<p>
    <a asp-action="Details" asp-route-slug="@Model.Event.Slug" class="btn btn-outline-secondary">Back to Event</a>
</p>

<table class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Product</th>
            <th>Winner</th>
            <th>Winning Amount</th>
            <th>Time</th>
        </tr>
    </thead>
    @foreach(var bid in Model.WinningBids)
    {
        <tr>
            <td>
                <strong>@bid.ProductName</strong>
            </td>
            <td>
                <strong>@bid.Winner.FullName</strong><br />
                @if (!string.IsNullOrEmpty(bid.Winner.Address))
                {
                    @bid.Winner.Address<br />
                    @if (!string.IsNullOrEmpty(bid.Winner.Address2))
                    {
                        @bid.Winner.Address2<br />
                    }
                    @($"{bid.Winner.City}, {bid.Winner.State} {bid.Winner.PostalCode}")<br />
                }
                else
                {
                    <i>No address provided</i><br />
                }

                @if (!string.IsNullOrEmpty(bid.Winner.PhoneNumber))
                {
                    @bid.Winner.PhoneNumber
                }
                else
                {
                    <i>No phone number provided</i>
                }
            </td>
            <td>@bid.BidAmount.ToString("c2")</td>
            <td>@bid.BidTimestamp.ToString("g")</td>
        </tr>
    }
</table>

Bidster/Views/Events/_EditForm.cshtml
@model Bidster.Models.Events.EditEventViewModel

<div class="form-group">
    <label asp-for="Name"></label>
    <input type="text" asp-for="Name" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="Description"></label>
    <kendo-editor for="Description" deferred="true" encoded="false">
        <tools>
            <tool name="formatting" />
            <tool name="bold" />
            <tool name="italic" />
            <tool name="underline" />
            <tool name="insertUnorderedList" />
            <tool name="insertOrderedList" />
            <tool name="indent" />
            <tool name="outdent" />
            <tool name="createLink" />
            <tool name="unlink" />
        </tools>
    </kendo-editor>
</div>
<div class="form-group">
    <label asp-for="StartOn" class="form-label"></label>
    <kendo-datetimepicker for="StartOn" deferred="true" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="EndOn"></label>
    <kendo-datetimepicker for="EndOn" deferred="true" class="form-control" />
</div>
<div class="form-group">
    <label asp-for="DisplayOn"></label>
    <kendo-datetimepicker for="DisplayOn" deferred="true" class="form-control" />
    <span class="text-muted">Enter the date on which you would like this event to appear on the site.</span>
</div>
<div class="form-group">
    <label asp-for="DefaultMinimumBidAmount"></label>
    <input type="text" asp-for="DefaultMinimumBidAmount" class="form-control" />
    <span class="text-muted">If set, new items for this event will use this as the min. bid amount. Value can be changed per item.</span>
</div>
<div class="checkbox">
    <label asp-for="HideBidderNames">
        <input asp-for="HideBidderNames" />
        Hide bidder names
        <span class="text-muted">(Names are still visible to event admins)</span>
    </label>
</div>